version: "3.8"

services:
  web:
    image: nginx:latest
    container_name: auth-web-service
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./auth-service:/var/www/html/auth-service:rw
    ports:
      - "5001:80"
    networks:
      - microservices-network
    depends_on:
      - auth-service

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    volumes:
      - ./auth-service:/var/www/html/auth-service:rw
    environment:
      - APP_ENV=dev
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB=auth_db
      - SERVICE_NAME=auth-service
    expose:
      - "9000"
    depends_on:
      - mongodb
    networks:
      - microservices-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGODB_DATABASE=microservices_db
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password123
    ports:
      - '27017:27017'
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mongodb_data:
