security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        mongodb_users:
            mongodb:
                class: App\Document\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            lazy: true
            provider: mongodb_users
            
            # Configuração para JWT
            jwt: true
            
            # Configuração de logout
            logout:
                path: auth_logout
                
            # Configuração JSON login
            json_login:
                check_path: auth_login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

    # Regras de acesso atualizadas
    access_control:
        # Rotas públicas
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        
        # Rotas protegidas
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }
        - { path: ^/admin, roles: ROLE_ADMIN, requires_channel: https }
        
        # Proteção adicional para rotas sensíveis
        - { path: ^/api/user, roles: ROLE_USER, requires_channel: https }
        - { path: ^/api/profile, roles: ROLE_USER, requires_channel: https }

    # Configurações de segurança role hierarchy
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

# Configurações adicionais recomendadas
when@dev:
    security:
        firewalls:
            main:
                security: false

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10